# Generated by Django 4.1.7 on 2023-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(help_text='item', max_length=64, verbose_name='menu_item')),
                ('slug', models.SlugField(help_text='Адрес сообщест', unique=True, verbose_name='Адрес для страницы с постами')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
